### PR TITLE
New navbar

### PR DESCRIPTION
**Pull request by siviyn**
Added new navbar to improve interface, especially on mobile devices. The new navbar now does not take up half the screen on a phone, when the screen size is too small the navbar becomes a dropdown menu.

### CODE REVIEW

**Comment by siviyn** [comment]
Need to fix size consistency between pages and the hoe button being higher than it should be

**Review by colatkinson — CHANGES_REQUESTED** [review]
Top navbar has inconsistent sizing on different pages, and when logged in vs not. Additionally, the home button is slightly higher up than the others.

**Comment by siviyn** [comment]
Issues on previous comments have been fixed

**Comment by jemzlee** [comment]
looks great

**Comment by jemzlee** [comment]
Changes look good and addressed colin's issues. You are beautiful

**Comment by Jacob-Lane** [comment]
If this pull request was a pizza, it would be a pineapple and ham pizza.

**Comment by Jacob-Lane** [comment]
I give it a 5/7 stars.

**Comment by Jacob-Lane** [comment]
🅱️eep 🅱️eep Lettuce

**Comment by Jacob-Lane** [comment]
it's 4 2 0 today 😳 😱 but I'm not smoking weed 🌿 🍁 😏 🚬 I'm smoking 💨 😜 the bible 😇 🙏 📕 because heaven ⬆️ 😍 👐 😂 is the highest you can get 🙌 😤

**Comment by colatkinson** [comment]
Navbar height still changes depending on whether you're logged in or not

**Comment by siviyn** [comment]
Fixed everything pls approve----- nvm let me fix the rest

**Review by ghost — APPROVED** [review]
Looks good

**Review by colatkinson — COMMENTED** [review]
🅱️ool and good

**Pull request merged**
